### ISSUE TITLE
Investigate how to migrate Prometheus PVCs

### ISSUE THREAD

**Issue by wyb1** [gardener/monitoring#16]
**What would you like to be added**:

Investigate if it is possible for a Prometheus managed by the `prometheus-operator` to "reuse" a PVC that previously belonged to a Prometheus *not* managed by the operator.

**Why is this needed**:

Migration to the `prometheus-operator`.

**Comment by wyb1** [comment]
It is possible for a `Prometheus` to use an arbitrary `pvc` with 
```
  volumes:
  - name: prometheus-prometheus-db
    persistentVolumeClaim:
      claimName: prometheus-db-prometheus-0
```

**Comment by wyb1** [comment]
It is not possible to overwrite the flag `--storage.tsdb.path` which would be needed.

**Comment by wyb1** [comment]
Migration works!

Steps:

1. Find the pv that belongs to the "old" pvc and and set the `pv`'s `persistentVolumeReclaimPolicy=Retain` 
2. Delete the "old" pvc. The pv should still exist.
3. Reference the pv in the new pvc that is defined in the `Prometheus` object.
  ```yaml
    storage:
      volumeClaimTemplate:
        apiVersion: v1
        metadata:
          labels:
            app: prometheus
            role: monitoring
          name: prometheus-db
        spec:
          volumeName: <existing-pv>
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: default
          volumeMode: Filesystem
  ```
4. Prometheus will require an init container to migrate the data. The "old" prometheus had its data stored in the `subPath=/prometheus-`. The new prometheus will store it in the `subPath=/prometheus-db`. So if we mount the volume in a container with no subPath the structure will look like this:

/
/prometheus-/<old-prometheus-data>
 
  ```yaml
    initContainers:
    - name: alpine
      image: alpine
      command:
      - sh
      - -c
      - <verify /prometheus/prometheus-db is empty and mv data from /prometheus/prometheus- /prometheus/prometheus-db>
      volumeMounts:
      - mountPath: /prometheus
        name: prometheus-db
  ```
